version: "3"
services:
  backend: 
    build: backend
    ports:
      - 80:80
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    image: "mariadb:10.11"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - private
    volumes:
      - db_data:/var/lib/mysql
  proxy:
    image: "nginx:1.25"
    ports:
      - "3000:3000"
    networks:
      - public
    depends_on: 
      - backend
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true

volumes:
  db_data:

networks:
  public:
  private:




    